"""
LLM 模块

提供 LLM 客户端和 Prompt 管理
"""

from .client import LLMClient, get_llm_client
from .prompts import (
    QUERY_REWRITE_PROMPT,
    CONTEXT_REWRITE_PROMPT,
    HYDE_PROMPT,
    ANSWER_GENERATION_PROMPT,
    ANSWER_GENERATION_SYSTEM_PROMPT,
    FAITHFULNESS_EVAL_PROMPT,
    RELEVANCY_EVAL_PROMPT,
    IDENTITY_RESPONSE,
    NO_CONTEXT_RESPONSE,
    GENERATION_ERROR_RESPONSE,
)

__all__ = [
    "LLMClient",
    "get_llm_client",
    "QUERY_REWRITE_PROMPT",
    "CONTEXT_REWRITE_PROMPT",
    "HYDE_PROMPT",
    "ANSWER_GENERATION_PROMPT",
    "ANSWER_GENERATION_SYSTEM_PROMPT",
    "FAITHFULNESS_EVAL_PROMPT",
    "RELEVANCY_EVAL_PROMPT",
    "IDENTITY_RESPONSE",
    "NO_CONTEXT_RESPONSE",
    "GENERATION_ERROR_RESPONSE",
]
